config/routes.rb
Website::Application.routes.draw do

  get "ratings/update"
  resources :line_items
  resources :plans
  get "places_list/index"

resources :ratings, only: :update
resources :locations
resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/population' => 'welcome#population'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :population
     resources :survey

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
    belongs_to :user
  	validates :user_id, presence: true
    validates :description, presence: true, length: { maximum: 140 }
  	default_scope -> { order('created_at DESC') }
  	translates :title, :description
    has_many :ratings

        
    def average_rating
    ratings.sum(:score) / ratings.size
    end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :location
  belongs_to :plan
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
  #ensure that there are no line items referencing this location
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_location(location_id)
    current_item = line_items.find_by(location_id: location_id)
    if current_item
      current_item = current_item
    else
      current_item = line_items.build(location_id: location_id)
    end
    current_item
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments
  has_many :ratings
  has_many :comments
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy if @plan.id == session[:plan_id]
    session[:cart_id] = nil|
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Your plan is empty'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params[:plan]
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def update
    @rating = Rating.find(params[:id])
    @comment = @rating.comment
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def new
		@user = User.new
	end

	def index
		@user= User.find(:all)
	end

	def show
		@user = User.find(params[:id])
	end

	def create 
		@user = User.new(user_params)

		if @user.save
			flash[:notice] = "User succesfully created"
			redirect_to @user
		else
			render action: 'new'
		end
	end

	def update
		super
	end

	def destroy
		@user.destroy
		redirect_to users_url, notice: 'User was successfully destroyed.'
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
     @locations = Location.order(:title)
   end
 	
 	def help
  end

   def whats
  end

   def about
  end

   def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_list_helper.rb
module PlacesListHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<h2> Your Plan </h2>
    <table>
      <%= render(@plan.line_items) %>
    </table>
        <%= link_to 'Destroy', @plan, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to t('.print') %>
        <%= link_to t('.email') %>
        <%= link_to 'Back', places_list_index_path %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<div class="plans_content">
  <h1>Listing plans</h1>
    <table>
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @plans.each do |plan| %>
          <tr>
            <td><%= link_to 'Show', plan %></td>
            <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
            <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <br>

  <%= link_to 'New Plan', new_plan_path %>
</div>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<% if notice %>
<p id= 'notice'><%= notice %></p>
<% end %>
<div class="plans_content">
  <%=render @plan %>
</div>

app/views/ratings/update.html.erb
<h1>Ratings#update</h1>
<p>Find me in app/views/ratings/update.html.erb</p>