config/routes.rb
Website::Application.routes.draw do

  get "ratings/update"
  resources :line_items
  resources :plans
  get "places_list/index"

resources :ratings, only: :update
resources :locations
resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/population' => 'welcome#population'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :population
     resources :survey

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
    belongs_to :user
  	validates :user_id, presence: true
    validates :description, presence: true, length: { maximum: 140 }
  	default_scope -> { order('created_at DESC') }
  	translates :title, :description
    has_many :ratings

        
    def average_rating
    ratings.sum(:score) / ratings.size
    end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :location
  belongs_to :plan
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
  #ensure that there are no line items referencing this location
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_location(location_id)
    current_item = line_items.find_by(location_id: location_id)
    if current_item
      current_item = current_item
    else
      current_item = line_items.build(location_id: location_id)
    end
    current_item
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments
  has_many :ratings
  has_many :comments
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
      @locations = Location.all
      @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end
  
  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy if @plan.id == session[:plan_id]
    session[:cart_id] = nil|
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Your plan is empty'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params[:plan]
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def update
    @rating = Rating.find(params[:id])
    @comment = @rating.comment
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def new
		@user = User.new
	end

	def index
		@user= User.find(:all)
	end

	def show
		@user = User.find(params[:id])
	end

	def create 
		@user = User.new(user_params)

		if @user.save
			flash[:notice] = "User succesfully created"
			redirect_to @user
		else
			render action: 'new'
		end
	end

	def update
		super
	end

	def destroy
		@user.destroy
		redirect_to users_url, notice: 'User was successfully destroyed.'
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_list_helper.rb
module PlacesListHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.address %></td>
        <td><%= location.description %></td>
        <td><%= location.title %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 <div class= "maps" style='width: 800px;'>
   <div id="map" style='width: 800px; height: 400px;'></div>
 </div>

<br>

<%= link_to 'New Location', new_location_path %>

<script type= "text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'basic_map' }}); function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div class = "detail_location">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @location.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>


<!--<%= link_to 'Edit', edit_location_path(@location) %> | -->
<%= link_to 'Back', places_list_index_path %>
</div>