config/routes.rb
Website::Application.routes.draw do

  get "ratings/update"
  resources :line_items
  resources :plans
  get "places_list/index"

resources :ratings, only: :update
resources :locations
resources :comments
resources :attractions
resources :welcome

devise_for :admins
devise_for :users , controllers: {users: 'users', sessions: 'sessions'}

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'
  get '/population' => 'welcome#population'
  get '/survey' => 'welcome#survey'
  get '/help' => 'welcome#help'
  get '/contact' => 'welcome#contact'
 
  devise_scope :user do

 get '/signup' => 'devise/registrations#new'
 get '/signin' => 'devise/sessions#new'
 post 'users/sign_in' => 'sessions#create'
 get'/users/sign_out' => 'sessions#destroy'
  end

  scope "(:locale)" do
     resources :index
     resources :about
     resources :help
     resources :contact
     resources :population
     resources :survey

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/attraction.rb
class Attraction < ActiveRecord::Base

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
    belongs_to :user
  	validates :user_id, presence: true
    validates :description, presence: true, length: { maximum: 140 }
  	default_scope -> { order('created_at DESC') }
  	translates :title, :description
    has_many :ratings

        
    def average_rating
    ratings.sum(:score) / ratings.size
    end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :location
  belongs_to :plan
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
  has_many :line_items
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
  #ensure that there are no line items referencing this location
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  
  def add_location(location_id)
    current_item = line_items.find_by(location_id: location_id)
    if current_item
      current_item = current_item
    else
      current_item = line_items.build(location_id: location_id)
    end
    current_item
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments
  has_many :ratings
  has_many :comments
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy if @plan.id == session[:plan_id]
    session[:cart_id] = nil|
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Your plan is empty'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params[:plan]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/places_list_helper.rb
module PlacesListHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="large-12 columns">
      <div class="row">
        <div class="large-4 columns">
          <p><a href="">Ecuador Travel</a> by Andrea Becerra</p>
        </div>
        <div class="large-4 columns">
          <p><%= link_to t('.about'),   about_path %></p>
        </div>

        <div class="large-4 columns">
          <p><%= link_to t('.help'), contact_path %></p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<div class = "header">
  <div class = "headerUp">
    <div class = "logo">
      <%= image_tag("logo.png") %>
    </div>
    <div class ="header-right">
      <nav class="top-bar"> 
        <section class="top-bar-section">
        <!-- Right Nav Section -->
          <ul class="right">
            <li class= "has-form">
              <div class = "language">
                <%= form_tag(root_url, class: 'locale') do %>
                <%= select_tag(:LANGUAGES, options_for_select([['Español', 1], ['English', 2]])) %>
                <% end %>
              </div>
            </li>
            <li class="divider"></li>
            <li class= "has-form">
              <div class= "row_login">
                  <div class="column_left">
                    <%= link_to  t('.signup'), new_user_registration_path, :class=> "button radius" %>
                  </div>
                  <div class="column_right">
                    <%= link_to  t('.signin'), new_user_session_path, :class=> "button radius" %>
                  </div>
              </div>
            </li>
            <li class="divider"></li>
            <li class= "has-form">
              <div class = "search">
                <div class="row collapse">
                  <div class="large-7 small-9 columns">
                    <%= form_tag("/search", method: "get") do %>
                    <%= text_field_tag(:q) %>
                  </div>
                  <div class="large-5 small-3 columns">
                    <%= submit_tag("Search", class: "button radius round")%>
                    <% end %>  
                  </div>
                </div>       
              </div>
            </li>
          </ul> 
        </section>
      </nav> 
    </div>
    <div class = "banner">
      <%= image_tag("advertice.png") %>
    </div>
    <!--<div class = "follow">
        <ul class="layout">
          <li class="iconfacebook">
          <a href="https://www.facebook.com/andrea.becerra.712161" class="btn png_bg" title="Facebook" target="_blank">.</a>
          </li>
           <li class="icontwitter">
          <a href="https://www.facebook.com/andrea.becerra.712161" class="btn png_bg" title="Facebook" target="_blank"                                           onclick="ntptEventTag('ev=snsLead&SNSId=facebook');">F</a>
          </li>
           <li class="icongoogle">
          <a href="https://www.facebook.com/andrea.becerra.712161" class="btn png_bg" title="Facebook" target="_blank"                                           onclick="ntptEventTag('ev=snsLead&SNSId=facebook');">F</a>
          </li>
           <li class="iconyoutube">
          <a href="https://www.facebook.com/andrea.becerra.712161" class="btn png_bg" title="Facebook" target="_blank"                                           onclick="ntptEventTag('ev=snsLead&SNSId=facebook');">F</a>
          </li>
        </ul>
      </div>-->
  </div>

  <div class = "menu">
   <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to t('.name'), root_path, id: "logo" %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li><%= link_to_unless I18n.locale == :es, "Español", locale: :es %></li>
        <li><%= link_to_unless I18n.locale == :en, "English", locale: :en %></li>
        <li class="active"><%= link_to  t('.home'), root_url %></li>
        <li class= "has-dropdown"><%= link_to  t('.ecuador') %>
          <ul class="dropdown">
            <li class= "has-dropdown"><%= link_to  t('.info') %>
               <ul class="dropdown">       
                 <li><%= link_to  t('.population'), population_path %></li>
                 <li><%= link_to  t('.regions'), new_user_registration_path %></li>
                 <li><%= link_to  t('.wheater'), new_user_registration_path %></li>
                 <li><%= link_to  t('.money'), new_user_registration_path %></li>
               </ul>
            </li>
            <li class= "has-dropdown"><%= link_to  t('.culture'), new_user_registration_path %></li>
             <ul class="dropdown">       
                 <li><%= link_to  t('.population'), new_user_registration_path %></li>
                 <li><%= link_to  t('.regions'), new_user_registration_path %></li>
                 <li><%= link_to  t('.wheater'), new_user_registration_path %></li>
                 <li><%= link_to  t('.money'), new_user_registration_path %></li>
               </ul>
            <li class= "has-dropdown"><%= link_to  t('.landscape'), new_user_registration_path %></li>
             <ul class="dropdown">       
                 <li><%= link_to  t('.population'), new_user_registration_path %></li>
                 <li><%= link_to  t('.regions'), new_user_registration_path %></li>
                 <li><%= link_to  t('.wheater'), new_user_registration_path %></li>
                 <li><%= link_to  t('.money'), new_user_registration_path %></li>
               </ul>
          </ul>
        </li>
        <li class="has-dropdown"><%= link_to  t('.places'), places_list_index_path  %>
          <ul class="dropdown">   
            <li class="has-dropdown"><%= link_to  t('.galapagos'), new_user_registration_path %>
              <ul class="dropdown">  
                <li><%= link_to  t('.isabela'), places_list_index_path %></li>
                 <li><%= link_to  t('.sancristobal'), new_user_registration_path %></li>
                 <li><%= link_to  t('.santacruz'), new_user_registration_path %></li>
              </ul>
             </li>
             <li class="has-dropdown"><%= link_to  t('.pacific'), new_user_registration_path %>
              <ul class="dropdown">  
                <li><%= link_to  t('.esmeraldas'), new_user_registration_path %></li>
                <li><%= link_to  t('.manabi'), new_user_registration_path %></li>
                 <li><%= link_to  t('.guayas'), new_user_registration_path %></li>
                <li><%= link_to  t('.losrios'), new_user_registration_path %></li>
                <li><%= link_to  t('.eloro'), new_user_registration_path %></li>
                <li><%= link_to  t('.santaelena'), new_user_registration_path %></li>
              </ul>
             </li>
            <li class="has-dropdown"><%= link_to  t('.amazon'), new_user_registration_path %>
              <ul class="dropdown">  
                 <li><%= link_to  t('.sucumbios'), new_user_registration_path %></li>
                 <li><%= link_to  t('.napo'), new_user_registration_path %></li>
                 <li><%= link_to  t('.pastaza'), new_user_registration_path %></li>
                 <li><%= link_to  t('.orellana'), new_user_registration_path %></li>
                 <li><%= link_to  t('.moronasantiago'), new_user_registration_path %></li>
                 <li><%= link_to  t('.zamorachinchipe'), new_user_registration_path %></li>
              </ul>
             </li>
            <li class="has-dropdown"><%= link_to  t('.andes'), new_user_registration_path %>
              <ul class="dropdown">  
                 <li><%= link_to  t('.carchi'), new_user_registration_path %></li>
                 <li><%= link_to  t('.imbabura'), new_user_registration_path %></li>
                 <li><%= link_to  t('.pichincha'), new_user_registration_path %></li>
                <li><%= link_to  t('.cotopaxi'), new_user_registration_path %></li>
                <li><%= link_to  t('.tungurahua'), new_user_registration_path %></li>
                <li><%= link_to  t('.bolivar'), new_user_registration_path %></li>
                <li><%= link_to  t('.chimborazo'), new_user_registration_path %></li>
                <li><%= link_to  t('.cañar'), new_user_registration_path %></li>
                <li><%= link_to  t('.azuay'), new_user_registration_path %></li>
                <li><%= link_to  t('.loja'), new_user_registration_path %></li>
                <li><%= link_to  t('.santodomingo'), new_user_registration_path %></li>
                
              </ul>
             </li>
            </ul>
          </li>
        <li class="has-dropdown"><%= link_to  t('.do'), locations_path %>
          <ul class="dropdown">  
            <li><%= link_to  t('.gastronomy'), new_user_registration_path %></li>
            <li><%= link_to  t('.culture'), new_user_registration_path %></li>
            <li><%= link_to  t('.adventure'), new_user_registration_path %></li>
            <li><%= link_to  t('.shoping'), new_user_registration_path %></li>
          </ul>
        </li>
        <li><%= link_to  t('.hotelsrestaurant'), locations_path %></li>
        <li class= "has-dropdown"><%= link_to t('.plan'), attractions_path %>
          <ul class="dropdown">
            <li class= "has-dropdown"><%= link_to t('.before'), attractions_path %>
               <ul class="dropdown">
                 <li><%= link_to  t('.trip_planner'), plans_path %></li>
                 <li><%= link_to  t('.visa'), new_user_registration_path %></li>
                 <li><%= link_to  t('.visa'), new_user_registration_path %></li>
               </ul>
            </li>
             <li class= "has-dropdown"><%= link_to t('.before'), attractions_path %>
               <ul class="dropdown">
                 <li><%= link_to  t('.visa'), new_user_registration_path %></li>
                 <li><%= link_to  t('.visa'), new_user_registration_path %></li>
                 <li><%= link_to  t('.visa'), new_user_registration_path %></li>
               </ul>
            </li>
          </ul>
        </li>
          <li><%= link_to t('.comments'), comments_path %></li>
         <% if user_signed_in? %>
      
        <li class="has-dropdown">
          <a href="#"><%= t('.account') %></a>
          <ul class="dropdown">
            <li><%= link_to  t('.profile'), '#' %></li>
            <li><%= link_to  t('.edit'), edit_user_registration_path %></li>
            <li><%= link_to  t('.signout'), destroy_user_session_path, method: "delete" %></li>
             
              <% end %>
          </ul>
        </li>
       </ul>
     </section>
   </nav>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Website" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Website" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>